apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z415hf3de-nodejs
  janus-idp.io/tekton: z415hf3de-nodejs
  backstage.io/kubernetes-id: z415hf3de-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z415hf3de-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
